### ISSUE TITLE
Is transition(new_state) like function available?

### ISSUE THREAD

**Issue by kapilpipaliya** [merqlove/ecto_state_machine#2]
I want to transition from previous state to next state. I have a Api only phoenix application. data is comming from api. so its very helpful if i have a function to change state by one function.

**Comment by merqlove** [comment]
@kapilpipaliya , Hello. You talking about transition to the next state, if available? Good thing!
For now here is no such method, but you can easily add it. 
PR is welcome!

**Comment by kapilpipaliya** [comment]
yes. can you please explain more how to make function? i am not expert.

**Comment by merqlove** [comment]
@kapilpipaliya, look this branch. Use parameter `inline: true` to enable this functionality.
As result you will have method next_state. Remember it is non-reversible method. Only one way is supported.
https://github.com/cnsa/ecto_as_state_machine/tree/AddNextStateSupport

**Comment by kapilpipaliya** [comment]
Thanks.
if not existing state is passed to next_state function. it gives error:
`(FunctionClauseError) no function clause matching in Ecto.Changeset.change/2  `
I also want function can_transition(new_state) function.
I also want prefix support if the library make any database update.

**Comment by kapilpipaliya** [comment]
previously i was using [statesman](https://github.com/gocardless/statesman) library.

**Comment by merqlove** [comment]
@kapilpipaliya prefix support is here already. Read the doc's. https://hexdocs.pm/ecto_as_state_machine/EctoAsStateMachine.Helpers.html

I released new version, with fixed specs for this functionality.
`:next_state` method description now here:
https://github.com/cnsa/ecto_as_state_machine#next-state
